# Generated by Django 5.0.1 on 2024-02-05 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('manual', models.FileField(upload_to='manuals/')),
                ('uploader', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='area_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Area_Common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField()),
                ('research_school_career', models.IntegerField()),
                ('overseas_citizen_institution', models.IntegerField()),
                ('training_year', models.IntegerField()),
                ('school_violence', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Common_Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_year', models.IntegerField(blank=True, null=True)),
                ('career_month', models.IntegerField(blank=True, null=True)),
                ('career_memo', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Common_Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade1teacher_result', models.IntegerField(blank=True, null=True)),
                ('grade1teacher_memo', models.TextField(blank=True, null=True)),
                ('training_first', models.IntegerField(blank=True, null=True)),
                ('training_second', models.IntegerField(blank=True, null=True)),
                ('training_memo', models.TextField(blank=True, null=True)),
                ('research_contest_point', models.IntegerField(blank=True, null=True)),
                ('degree_point', models.IntegerField(blank=True, null=True)),
                ('research_memo', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Common_WorkPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_late_1', models.IntegerField(blank=True, null=True)),
                ('wp_late_2', models.IntegerField(blank=True, null=True)),
                ('wp_late_3', models.IntegerField(blank=True, null=True)),
                ('wp_late_4', models.IntegerField(blank=True, null=True)),
                ('wp_late_5', models.IntegerField(blank=True, null=True)),
                ('wp_memo', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField()),
                ('point_cc', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True)),
                ('point_cw', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True)),
                ('point_ct', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True)),
                ('point_ac', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True)),
                ('point_as', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=8, max_digits=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
