# Generated by Django 5.0.1 on 2024-01-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area_difference',
        ),
    ]
