# Generated by Django 5.0.1 on 2024-01-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_profile_point_ac_alter_profile_point_as_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='common_carrer',
            name='career_month_over',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='common_carrer',
            name='career_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
