# Generated by Django 5.0.1 on 2024-02-17 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_suggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='point_as',
        ),
        migrations.AddField(
            model_name='profile',
            name='point_ad',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='common_career',
            name='career_memo',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='common_career',
            name='career_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='common_career',
            name='career_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='common_training',
            name='grade1teacher_memo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='common_training',
            name='research_memo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='common_training',
            name='training_memo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='common_workperformance',
            name='wp_late_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='common_workperformance',
            name='wp_late_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='common_workperformance',
            name='wp_late_3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='common_workperformance',
            name='wp_late_4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='common_workperformance',
            name='wp_late_5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='common_workperformance',
            name='wp_memo',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='point_ac',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='point_cc',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='point_ct',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='point_cw',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=100, null=True),
        ),
        migrations.CreateModel(
            name='Area_Diff_Jeonnam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island_ga_year', models.IntegerField(default=0)),
                ('island_ga_month', models.IntegerField(default=0)),
                ('island_na_year', models.IntegerField(default=0)),
                ('island_na_month', models.IntegerField(default=0)),
                ('island_da_year', models.IntegerField(default=0)),
                ('island_da_month', models.IntegerField(default=0)),
                ('island_ra_year', models.IntegerField(default=0)),
                ('island_ra_month', models.IntegerField(default=0)),
                ('mountain_ga_year', models.IntegerField(default=0)),
                ('mountain_ga_month', models.IntegerField(default=0)),
                ('mountain_na_year', models.IntegerField(default=0)),
                ('mountain_na_month', models.IntegerField(default=0)),
                ('mountain_da_year', models.IntegerField(default=0)),
                ('mountain_da_month', models.IntegerField(default=0)),
                ('mountain_ra_year', models.IntegerField(default=0)),
                ('mountain_ra_month', models.IntegerField(default=0)),
                ('outside_school_memo', models.TextField(default='')),
                ('rural_1_year', models.IntegerField(default=0)),
                ('rural_1_month', models.IntegerField(default=0)),
                ('rural_2_year', models.IntegerField(default=0)),
                ('rural_2_month', models.IntegerField(default=0)),
                ('rural_3_year', models.IntegerField(default=0)),
                ('rural_3_month', models.IntegerField(default=0)),
                ('rural_add_month', models.IntegerField(default=0)),
                ('rural_memo', models.TextField(default='')),
                ('high_teacher_year', models.IntegerField(default=0)),
                ('high_teacher_add_year', models.IntegerField(default=0)),
                ('high_teacher_memo', models.TextField(default='')),
                ('research_school_area_year', models.IntegerField(default=0)),
                ('research_school_area_month', models.IntegerField(default=0)),
                ('research_school_area2_year', models.IntegerField(default=0)),
                ('research_school_area2_month', models.IntegerField(default=0)),
                ('research_school_area_memo', models.TextField(default='')),
                ('double_class_year', models.IntegerField(default=0)),
                ('double_class_month', models.IntegerField(default=0)),
                ('cyber_year', models.IntegerField(default=0)),
                ('cyber_month', models.IntegerField(default=0)),
                ('genius_year', models.IntegerField(default=0)),
                ('genius_month', models.IntegerField(default=0)),
                ('intern_month', models.IntegerField(default=0)),
                ('intern_day', models.IntegerField(default=0)),
                ('scout_month', models.IntegerField(default=0)),
                ('competition_gold_point', models.IntegerField(default=0)),
                ('competition_silver_point', models.IntegerField(default=0)),
                ('competition_bronze_point', models.IntegerField(default=0)),
                ('cert_1_point', models.IntegerField(default=0)),
                ('cert_2_point', models.IntegerField(default=0)),
                ('cert_3_point', models.IntegerField(default=0)),
                ('edupower_count', models.IntegerField(default=0)),
                ('openclass_add_count', models.IntegerField(default=0)),
                ('high_teacher_add_plus_count', models.IntegerField(default=0)),
                ('etc_memo', models.TextField(default='')),
                ('openclass_count', models.IntegerField(default=0)),
                ('openclass_memo', models.TextField(default='')),
                ('living_solo_month', models.IntegerField(default=0)),
                ('living_solo_day', models.IntegerField(default=0)),
                ('living_family_month', models.IntegerField(default=0)),
                ('living_family_day', models.IntegerField(default=0)),
                ('living_memo', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='area_area',
        ),
    ]
