# Generated by Django 5.0.1 on 2024-01-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_common_carrer_career_month_over_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Common_carrer',
            new_name='Common_Career',
        ),
    ]
