# Generated by Django 5.0.1 on 2024-01-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_alter_area_common_user_alter_common_career_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='common_career',
            old_name='career_month_over',
            new_name='career_year',
        ),
    ]
