# Generated by Django 5.0.1 on 2024-02-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_notice_common_career_career_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common_workperformance',
            name='workperformance',
        ),
        migrations.AddField(
            model_name='common_workperformance',
            name='wp_late_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='common_workperformance',
            name='wp_late_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='common_workperformance',
            name='wp_late_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='common_workperformance',
            name='wp_late_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='common_workperformance',
            name='wp_late_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='common_workperformance',
            name='wp_memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
